### ISSUE TITLE
CLTK stopwords status

### ISSUE THREAD

**Issue by diyclassics** [aurelberra/stopwords#1]
@aurelberra—thanks for getting this conversation started. Quick update—the words given as CLTK stopwords are not intended to be final results. These are preliminary results collected for a conference paper on ongoing work. I have some updates that I can present soon (and contribute here), likely within the month (sorry, busy October!). Accordingly, I've opened this issue to keep track on my future contribution.

**Comment by aurelberra** [comment]
Thank you, @diyclassics! Please let me know when you are reasonably happy with your proposal.

I realise that naming "CLTK_xxx" the lists I took from your great Leipzig slides could be a bit confusing. I am fully aware that this is ongoing research, while the CLTK is currently using the original Perseus list.

Designing and evaluating stopwords lists is indeed a broader topic than the addition of a default, jack-of-all-trades list in Voyant Tools, which is the starting point here (cf. https://github.com/sgsinclair/Voyant/issues/382). We'll probably try to have a first version of Latin and Greek lists on the platform, and then revise it more thoughtfully. In any case, I'm happy see this discussion play out.

**Comment by aurelberra** [comment]
I have updated – in fact, [completely reworked](https://github.com/aurelberra/stopwords/blob/master/rationale.md) – these lists for Voyant Tools. Here or in the [Voyant issue](https://github.com/sgsinclair/Voyant/issues/382), I would be happy to have your opinion about the method I used. Given the constraints of the platform, this is a brute force philological approach compared to what the CLTK will offer, but I am happy with the results of my test!

**Comment by aurelberra** [comment]
I am very curious to see the new implementation of dynamic stopwords lists in CLTK! However, the methods are very different, since my lists for Voyant Tools are static, although they are informed by corpus analysis. So, I will close this issue for now – let's keep the discussion open, of course.
