### ISSUE TITLE
Supprimer νῷ de la Stoplist grecque

### ISSUE THREAD

**Issue by classicist** [aurelberra/stopwords#5]
Merci pour votre liste excellent! C'est un travail très utile.

En parcourant la liste, j'ai trouvé une erreur mineure: le mot νῷ est inclus dans la liste pour ἐγώ. Bien que cela soit sans aucun doute correct pour ce cas rare, la même forme représente le plus souvent le datif de νοῦς (par exemple dans des phrases comme ἐν νῷ εἶχον) et devrait donc peut-être être supprimée de la Stoplist.

**Comment by aurelberra** [comment]
Merci pour ce commentaire très juste ! Je n'ai pas systématiquement simplifié la liste en tenant compte de ce critère. Idéalement, il faudrait un contrôle statistique, mais en l'occurrence il semble clairement pertinent de supprimer le terme νῷ.

**Comment by aurelberra** [comment]
C'est fait (`stopwords_greek_v2_8`). Si vous apercevez d'autres termes problématiques, n'hésitez pas à le signaler.

Thanks again!

**Comment by classicist** [comment]
Pas de problem -- merci pour votre logiciel utile!
